# Site settings
title: Weber State University
subtitle: Stewart Library
email: specialcollections@weber.edu
description: Preserving Memories
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 3921 Central Campus Dr. Dept. 2901
city: Ogden 
state: UT
zip_code: 84408
country: United States of America
phone: (801) 626-6403

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/StewartLibrarySpecialCollections
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
